### ISSUE TITLE
BootStrap Theme/Support

### ISSUE THREAD

**Issue by w8tcha** [YAFNET/YAFNET#15]
Ok this will be a large task, adding support for bootstrap themes or move completely to bootstrap architecture.

I am currently in the process of making yaf ready for BootStrap, it is mostly adding CSS classes and adding div wrappers when necessary.

My current goal is to add bootstrap as additionally themes, to keep legacy support with the current themes.And in the long term i think the best way would be to move completely to almost table less designs and to bootstrap.

Feel free to leave any additionally ideas here

**Comment by Zero2Cool** [comment]
Everyone do happy dance, happy, happy dance!!!  http://v4-alpha.getbootstrap.com/

**Comment by w8tcha** [comment]
So the admin Interface is now converted to use Bootstrap. Some features in other areas are broken now. So i not recommend to Use 2.30 BETA in a production environment.

**Comment by JP58** [comment]
Admin interface looks very good to me, but when eg doing db maintenance task like reindexing it is still possible to press all kinds of buttons/menu items. Of course nothing happens since the reindex task is working. But how is it done in the background, are the pressed button/menu actions queued up in an async queue or ignored?   

Maybe a "busy spinner" or such would be in place for long running admin tasks.

**Comment by JP58** [comment]
Ooohhh...  Noticed the Admin -> Users & roles -> Search user still has some "table artefacts"...  ;-)

On PC, looks ok with the table.
![computer](https://cloud.githubusercontent.com/assets/5246746/17673593/18316c8c-6322-11e6-8317-eec4f63f9ca7.JPG)

On phone, the top selection row is "un-Bootstrapifyed" and is a table with a th row and a tr/td row instead of having the elements "bootstrapped"...  
Just a small detail...  ;-) 

![wp_ss_20160815_0001](https://cloud.githubusercontent.com/assets/5246746/17673700/9e53d9f8-6322-11e6-92bc-8bdb50fedf9d.png)
![wp_ss_20160815_0002](https://cloud.githubusercontent.com/assets/5246746/17673707/a36399ba-6322-11e6-858d-109908e25a96.png)

**Comment by w8tcha** [comment]
i think this way it looks better .. 
<img width="507" alt="usersearch" src="https://cloud.githubusercontent.com/assets/722575/17694426/2022ad02-63a4-11e6-82d9-fddd8eb551d8.PNG">

**Comment by JP58** [comment]
Of course it does.  :-) 
Would I then put the "user name" search term into the main search field, or will the field be added to the search dropdown pane?

**Comment by w8tcha** [comment]
i changed the drop down a little bit i think now its ok!

**Comment by w8tcha** [comment]
> Admin interface looks very good to me, but when eg doing db maintenance task like reindexing it is still possible to press all kinds of buttons/menu items. Of course nothing happens since the reindex task is working. But how is it done in the background, are the pressed button/menu actions queued up in an async queue or ignored?

> Maybe a "busy spinner" or such would be in place for long running admin tasks.

i added similar block ui messages that exist when you delete a forum

**Comment by JP58** [comment]
Will download & try the new stuff this weekend... :-)

**Comment by JP58** [comment]
Just an additional question - have you thought about using Angular in the future?
