### ISSUE TITLE
Feature - Suspension Tracker

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#204]
I would like an addition to the users profile that shows when they were suspended and for what duration. I think this would be wonderful to know how harsh to administer the next suspension or if its time for banishment. 

Perhaps this should be a second "issue", but with said tracker, also include the "reason" for suspension too.  I think this "reason" could be emailed to the user so they know why they were suspended and also in this email show how long they are suspended for. 

Edit, maybe a Suspended For drop-down list? 

Warning
Personal Attack
Name-calling
Spam
Abusing Moderator

I dunno ... something like that I think would be great.

**Comment by JP58** [comment]
I'm happy your forum has also reached the level of problems I have had for years...  ;-) 
It would be a great to have such a feature in the forum indeed. 

In my forum we practice a rule that each suspension is doubled the next time, but we do sometimes forget how long we suspended a particular user and start over from the beginning again if the user has behaved well for a longer period since the last time... 

But some years ago we had one user who managed to work up his "suspension penalty" from the initial 2 hrs to a full year....  ;-)))

It would indeed be great to have some kind of "suspension history table" within the forum software,
moderators would love it.

**Comment by w8tcha** [comment]
So i make some changes to the Admin -> Users & Roles -> Users Page.

* Admin Users page now shows if user is suspended and until which date
* On the Admin Users page you can now filter by suspended users to show only suspended users

> Add "Suspension" tab to Profile page.
Tab shows the "Suspend User 2 hours" as we currently have under "Moderated".

User Online Status icon now indicates if the user is suspended just like in the message post

Last Steps on the to do list
* Suspend Reason
* Notify user on suspension

**Comment by Zero2Cool** [comment]
is there a Suspension tab on the profile page? I'm looking but not seeing it.

**Comment by w8tcha** [comment]
> is there a Suspension tab on the profile page? I'm looking but not seeing it.

Not needed the online status image right next to the user name indicates if the user is suspended or not.

**Comment by Zero2Cool** [comment]
Oh, I thought the tab would show the previous suspension reasons. Ok good, I'm not missing anything then lol

**Comment by w8tcha** [comment]
Only when you edit the user then you see the current suspend reason on the "User Suspend" tab. But previous suspensions are not saved.
