### ISSUE TITLE
Feature - Report Private Message

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#216]
Might be a handy feature to add the ability to report a private message.

**Comment by JP58** [comment]
I'd say this would be great help for moderators to get to know the "bullies" who send ugly PM's to other members.  As it is now in my forum I get PM's that someone has been really offensive from a victim and have to look up the conversation directly in the db with sql statements. 

However, there is "moral" question here - should I go into the db and read PM messages? 
A report option would justify such actions, since it is a request to do it and I think it would 
be ok also "morally/legally".  A forum option to view the PM discussion between 2 members 
with the consent from one of the parties would be great as I see it.

**Comment by w8tcha** [comment]
I agree with JP, normal moderators should not allowed to view such messages. This should be only visible for host users.

But there is a need to report messages, since spammers now also use private messages!

I think the easiest solution would be to report a private message by sending a private message with the content to the host user!

**Comment by w8tcha** [comment]
added in 2.31.0
