### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#235]
Does YAF have an option to put the forum in maintenance mode so the website is live only to the administrator?  I know we can shut the site down via 'app_offline.htm', but that doesn't afford the admin the opportunity to do any live testing on the published site.  

If not a feature already (I might have missed it, I am terrible and finding those things, lol) I think it would be a solid addition. Especially when doing an update.

**Comment by JP58** [comment]
That is a stellar suggestion !!!  

Could it maybe be as "simple" as redirecting all users other than the "administrator" role to a static page at the "is the user logged on" check with a config checkbox in the admin pages? 

Or do you mean true single user mode? I think that would be more difficult coding-wise. 

I usually have some notifications while updating the forum software since it takes some time to upload the software and run the db migration. I get mails from my rather active users asking if the forum is down, why is there an "Enter config password" page and such... Would be better to have a page that informs users that the forum is in maintenance mode.

**Comment by Zero2Cool** [comment]
As an Admin, I'd be fine with users directed to a maintenance page.  
As an Admin, I would want something displaying the site was in maintenance mode as well. 

The forum would still be functional for the Admin (or moderators), but with a information box stating the forum is in maintenance mode. Therefore, you can still navigate towards the /install via Host Settings.

Does that make more sense?

**Comment by w8tcha** [comment]
Why not simply use an index.html as maintenance page and rename the default.aspsx or whatever the forum page is to something else. This is what I do. It is the simpliest solution, everything else is way to complex.

**Comment by Zero2Cool** [comment]
> Why not simply use an index.html as maintenance page and rename the default.aspsx or whatever the forum page is to something else. This is what I do. It is the simpliest solution, everything else is way to complex.

True, but then I have to use FTP or the host control panel instead of the YAF environment. :P 

I do see your point, the reward does not overvalue the effort.
