### ISSUE TITLE
Option to report all posts as spam when deleting a user.

### ISSUE THREAD

**Issue by PhonicUK** [YAFNET/YAFNET#237]
Right now if I want to report posts as spam back to Akismet, it's a very long process involving reporting each post individually, then going back to the moderation view to report them and delete them. This becomes very arduous when handling multiple posts.

It could be streamlined if there was an option to report all of a users posts to the active anti-spam service when deleting the user so that I don't have to chose between performing the reports to improve the service v.s. quickly dealing with the user.

**Comment by JP58** [comment]
There is a great reporting feature to StopForumSpam.com in the "Kill User" tab in the admin user dialog... Maybe there could be something similar for Aksimet too later on? 

My own stray thoughts: 
I myself have ditched the Aksimet option since all posts went to "moderator approval" in my forum, also the ones from well known users...  But maybe the new "bypass" option regarding spam-checking for users with a minimum of x number of posts can be extended to include Aksimet check exclusion too... 
So eg first 5 posts from a new user will be moderated, but ok after that...  Just a crazy idea...

**Comment by Zero2Cool** [comment]
I'm extremely pleased with the recent spam filtering, works great. 

At registration time, BotScout.com and StopForumSpam.com are used and then I only use the internal spam words filter for users with less than 20 posts. 

It has caught everything since implemented and made my admin life much gooder.

My only hesitation on a feature like this is what if you accidentally report the wrong user?

**Comment by w8tcha** [comment]
> I myself have ditched the Aksimet option since all posts went to "moderator approval" in my forum, also the ones from well known users... But maybe the new "bypass" option regarding spam-checking for users 

That issue has been fixed already.

> At registration time, BotScout.com and StopForumSpam.com are used and then I only use the internal spam words filter for users with less than 20 posts.

I agree and can confirm that this is the best solution. Akismet or BlogSpam appears to be useless so far.

@PhonicUK or did akismet ever catches any bots on your site?

**Comment by PhonicUK** [comment]
Akismet does catch some, according to their own stats anyway on my site.

**Comment by w8tcha** [comment]
unfortunately this cannot be added, i'm ging to remove The Report to akismet Feature completetly. At this Point it cannot work because the user agent string is not recorded with the message.

**Comment by JP58** [comment]
I think this is a very practical decision - since it's just one of the many services available and does not work well with the forum at all as I see it... 

I also use the same method as Zero2cool - botscout & stopforumspam at registration and then the internal spamwords...   Very few "bastards" make it nowadays, so my moderators are actually very happy if they can catch one that did...   ;-) 

Just a small esoteric idea - Would it be possible to schedule an automatic daily download from stopforumspam, unzip it and update the spam data within the forum software?

**Comment by w8tcha** [comment]
> Just a small esoteric idea - Would it be possible to schedule an automatic daily download from stopforumspam, unzip it and update the spam data within the forum software? 
Would save some manual work....

Well, it is possible but I wouldn't recommend it. Storing everything in the db, will blow up the database and is much slower then simply using the stopforumspam service.
