### ISSUE TITLE
Image attachments to posts.

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#239]
Have just downloaded the 2.2.0 to try it out before upgrading my forum... 

Was of course totally lost when there was no "Attach" button on the posts, but found the paper clip in edit mode. ;-) 

Great to be able to position attachments in posts and the new file upload is great, especially that you can select multiple images + drag & drop too. Also that previous attachments are shown so you can select an existing attachment to avoid duplicate uploads... The "Attach" bbcode tag design allows for editing your content, which is a absolutely great. 

However - there are 2 "small" issues as I see it... 
1 - You cannot cycle through attached images with prev-next as before. 
2 - Old posts with attachments do not show the "Attach" tag for attachments in posts.  

A 3rd issue would be that after attaching images, it would be nice to see the image also in edit mode, or at least a thumbnail when the attachment id is hovered so you know what pic you are making comments about...  

Just some stray thoughts...   :-)

**Comment by w8tcha** [comment]
> You cannot cycle through attached images with prev-next as before. 

Will be possible again in 2.2.1 (already added in the repository)

> Old posts with attachments do not show the "Attach" tag for attachments in posts.

This was/is a bit problematic because this needs an converting from the old message based attachments to the new inline attachments.

In 2.2.1 old attachments will show up in the editor with the bbcode when you edit that message. And automatically converted if the user saves the message.

> A 3rd issue would be that after attaching images, it would be nice to see the image also in edit mode, or at least a thumbnail when the attachment id is hovered so you know what pic you are making comments about...

Well this makes only sense with a WYSIWYG editor, writing a plugin for the CKEditor is still on my to do list. But this should be logged as new issue. 

So this one can be closed.
