### ISSUE TITLE
Message Auto Save Draft

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#256]
How about an ability for enabling an autosave? Lets say while typing your message gets auto saved to a "drafts" table.  One issue I have heard from folks who are more advanced in age is they spend 20 minutes typing a message and somehow they click a link or button or something and POOF it is gone. In this feature, if they open the thread again and hit reply, the text area would be populated by the message value that matches the topicID and their userID from the "drafts" table.

**Comment by JP58** [comment]
That would be a very nice feature indeed... 
My forum has several distinguished gentlemen of advanced age as members, and sometimes the session timeout hits them - or they simply forget to press the post button correctly...  

Has of course even happened to me too when I have had thinking breaks while composing that ultimate best worded post of all times in the forum...  Have learnt to copy/paste "slow" posts to Notepad before hitting the post button.... But of course forget it at times...  :-D  

Practical trouble would be that you will have to reserve a message id so it can't be used by another post that is posted while the "advanced age post" has yet to be completed since it would out of sequence... But it could also work if the draft is based only on the last unposted draft message per user & topic instead, and no message id is not set until posting... Means - only one draft per topic per user.

Maybe some kind of notification choice like "You have a post draft in this topic - Continue editing or Delete it? " instead of autofilling when opening the editor when hitting Reply?    

Just trying to think a bit how it could be done with minimum effort...  ;-)

**Comment by Zero2Cool** [comment]
I wouldn't think there be a MessageID used because the message would be a draft, so it would probably have a DraftID that would be associated to that user (by UserID) and by the topic (by TopicID) and definitely a notification would be beneficial. Maybe even have a draft clean up every X amount of days or something like that to ensure the database doesn't grow out of wicked control. 

I would wipe out corresponding drafts on a successful reply to the topic. So in the (this is not exact but to give an understanding) stored proc yafPost_save add in there to mark as deleted any drafts that correspond to the userID and TopicID. 

That's just a rough slap of keys explanation, but I think Ingo could come up with something more robust and intelligent with one eye shut.

**Comment by w8tcha** [comment]
> How about an ability for enabling an autosave?

I already build an ckeditor plugin for that, but instead of storing this in the db this uses the local browser localstorage db.

I enabled it in the last commit.

**Comment by Zero2Cool** [comment]
Unfortunately that ck editor is useless. Complete trash in my experience.

**Comment by w8tcha** [comment]
> Unfortunately that ck editor is useless. Complete trash in my experience.

Sorry but for me it is the opposite this is far better experience..
![Uploading ckeditor.png . . .]()

than that..
![Uploading standardEditor.png . . .]()

**Comment by Zero2Cool** [comment]
I fully agree that in a screen shot, it looks much better. However, it has to be useful as a tool and that it has not been for me in my experiences. I believe you work closely with that project and that is why I have made numerous attempts to make it work. I'll use it and list off my concerns with it and perhaps there is something I am simply missing that is ruining the experience.

**Comment by w8tcha** [comment]
> CK is missing Underline button near Bold and Italics (not a big deal, but just noticed it) 

Missing buttons are re-added now.

> and doesn't have the codes for Embed Twitter/Facebook (which I think would be great to add as buttons with admin configuration settings).

I have not forgotton about your request to render custom bbcodes to buttons from here
http://yetanotherforum.net/forum/posts/t13280-BBCode--YouTube--Spoiler

For now you can select all custom bbcodes from the drop down (this also works now in the CKEditor). The Idea would be to add a new option to custom bb codes to allow them as single button

> CK takes nearly a full second to load when the Standard is instant. That is so nice when you're in a rush. Mixing quotes, code and images is a lot smoother and easier with Standard than CK.

I'm aware of that trying to improve the loading time, without success so far, but i always use the quick reply function in such case.

> If you quote someone in CK, you can't break up that quote neatly to respond to different portions. The Standard editor, you can just copy/paste the quote=username tag and it's a breeze. To do this is CK you lose the name of whom you're quoting, although it could be inferred by the previous quote.

In that case you would need to switch to source mode, to avoid such problems.

**Comment by Zero2Cool** [comment]
Upgraded one of my test sites to the latest and the CK seems better using it as HTML instead of BBCode. 

When in a rush, it is not a rush to say something, it's a rush to help someone and in such cases I have to quote otherwise my rushed words will be even worse to read lol ... 

I really like using different font types with CK. Smooth.

**Comment by Zero2Cool** [comment]
I've been using the new CKEditor since you added some tweaks. I'm starting to like it. The BBCode version is kind of blah though. Definitely go HTML.

**Comment by w8tcha** [comment]
Message drafts will now be automatically saved. There is also a manually Save Button in the editor toolbar
