### ISSUE TITLE
YAF integration

### ISSUE THREAD

**Issue by Soul12** [YAFNET/YAFNET#317]
Hello,

first of all, congratulations to have built this forum software and thank you to offer it a an OpenSource licence. We did the same with our software.

We are working on integrating YAF into an OpenSource Learning and Content Management System (LCMS).

I have some issues about that integration. I did try to create an account on YAF forum in order to look at the topics but I have been rejected as a spam user. I don't understand why.

So, here are my issues:

- how to set a specific user as a moderator role for a specific forum ?
- how to hide the avatar and rank into the profile left section of the post page?
- is it possible to customize the CHAT in order to have private discussion with one user at a time (private chat).

Thank you in advance for your support.

Sylvain
Academic advisor

**Comment by w8tcha** [comment]
> I did try to create an account on YAF forum in order to look at the topics but I have been rejected as a spam user. I don't understand why.

The problem is your user name is in the spam database, the only solution would be to choose a different user name.

> how to set a specific user as a moderator role for a specific forum ?

You can do this by creating an moderator role and add the user to the moderator role. Or you assign the user directly. You can do that by going to the forum and click on the Moderate Button, right next to the New Topic Button. On that Moderate Page you can "Iinvite Users" and assign them directly with the Moderator Access Mask.

> how to hide the avatar and rank into the profile left section of the post page?

Go to the Host Settings and go to the Templates Tab and modify the User Box, this is the section. There you need to remove 

``` 
<yaf:avatar /><div class="section"><yaf:rankimage /><yaf:rank /></div><br />
```

> is it possible to customize the CHAT in order to have private discussion with one user at a time (private chat).

No, you can only send private messages, to users but no direct chat.
