### ISSUE TITLE
Register User Incorrect Validation Message

### ISSUE THREAD

**Issue by sslfto** [YAFNET/YAFNET#322]
In the User Creation Wizard, you cann type correct matching Password's-because the validation Message still appear: "Password and Confirm Password do not match!"
![image](https://cloud.githubusercontent.com/assets/14775789/13746085/e1780a7e-e9f1-11e5-97d6-419f16c19766.png)

**Comment by Zero2Cool** [comment]
What version are you using? I believe this was fixed in one of the recent commits.

**Comment by sslfto** [comment]
I use the Version 2.2.2 from the official download page.
You can see this behavior on the live site: http://www.yetanotherforum.net/forum/register

**Comment by Zero2Cool** [comment]
The commit I linked is after the official release. This issue was found out after that and Ingo fixed it right away.  The YAF site does not seem to get updated too often unless it's an official release. 

You can see here http://www.packershome.com/forum/register that the issue has been resolved, however, it has not been packaged in an official release yet.

**Comment by sslfto** [comment]
Thank you for quick help!
Exist´s a date for the next official release, or how can i apply the fix to my Installation?

**Comment by Zero2Cool** [comment]
What is suggested it to download the source, compile it and use the update package.  That's what I've been doing.

**Comment by w8tcha** [comment]
The new nightly builds for YAF 2.2.3 are online

https://github.com/YAFNET/YAFNET/releases/tag/v2.2.3.0-nightly.118
