### ISSUE TITLE
Cookie Law

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#326]
Does the Cookie law apply to YAF? I've noticed a lot of websites forcing users to acknowledge their cookie usage policy.  Maybe YAF has that and I just missed it?

https://www.cookielaw.org/faq/

**Comment by w8tcha** [comment]
Well first of all i really hate those annoying banners, so i don't think about adding this to the site.

When you register to the site you have to agree to the Rules and Policies, which also including information about the cookies.

I think the problem is that most people additionally add to there site, and also to the forum external scripts for example for Google analytics, or ads. Those scripts also store cookies. In that case the site owner would need to add a banner. But other then that in YAF itself i think its not necessary.

**Comment by Zero2Cool** [comment]
I think nearly every website has to use cookies, or does regardless. So basically the law is as worthwhile as saying if you're out side you're breathing air. And yes, those banners are annoying. They seem to always come back!
