### ISSUE TITLE
Version Upgrade

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#573]
I would like to suggest following version upgrades:

1. Jquery: Please upgrade it to latest version 3.5.1  (from 3.4.1), There is one small breaking change introduced in 3.5.0 due to security vulnerability.

2. NET Framework: Please consider upgrading to .Net 4.8 due to following reason:
a. This is the last major .net framework been released
b. .Net 4.8 was released in April 2019. By now all servers would have that version installed by default.
c. It has many feature improvement that makes the framework run much faster.

3. YAF Version: Could you combine version 2.32.0 with 2.31.7 and release 2.32 on June 28? All bugs in 2.32 have been closed since April and it has no open bugs. It would be great if you can release beta of 2.32 in few days to test.

4. Web.config: I would recommend merging different web.config files into one file. The azure config file is really not needed. The default (recommended) config file would work for all scenarios. Azure at beginning used to be different; but now they have made it compatible with standard windows server.

5. Any other upgrades (ckeditor, bootstrap, etc).

**Comment by w8tcha** [comment]
1. I'm working on it but I also need to update all scripts. Some scripts are incompatible at the moment. So this needs some work.

2. I plan to upgrade to 4.8 with yaf 3.0. Be aware that a lot of website still use 472 for example dnn. So an upgrade is not possible yet.

3. There is no version 2.32 anymore. It's now 3.00. And if you want to test it it can be downloaded from the ci server.

4. The azure web.config is needed at the moment. Because the yaf providers don't work with azure. With 3.0 it will no longer needed when the providers are no longer used

**Comment by john2014** [comment]
1. Awesome. Would it be possible to complete jquery upgrade when YAF 2.31.7 is released?

2. Per link below, DNN works with .Net 4.7.2 or above. So it should easily work with 4.8.
https://www.dnnsoftware.com/docs/developers/requirements.html

Did any of users say they are on software which only works till 4.7.2? It seems very unlikely that software which works for version 4.7.2 would not work for 4.8. If that is the case, the web.config file in /forum directory can be 4.8 and the main web.config in root directory can be 4.7.2. Problem solved.

3. Any idea when we can expect 3.0 to be released? One month or 3+ months?

**Comment by w8tcha** [comment]
1. Yes. By thee way you can change the version in the app settings in the app.config

2. Your solution with the web.configs wouldn't work because when you reference the dlls it won't work.

.net version upgrades will be only done for major version upgrades.

And yes from the errors message screen shots I can see which version is used

**Comment by w8tcha** [comment]
3. I try in q4 or q1 2021
