### ISSUE TITLE
Adding advisory messages

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#783]
There used to be advisory messages in the following sections.They are no longer but they need to be.
1-Deleting top level forum simply does nothing.No error. warning etc.In the old version there was a warning saying that "You must first delete child forums".
2-When user is suspended no message confirming the success or failure of operation is displayed.You need to check their profile to make sure they are suspended.

**Comment by w8tcha** [comment]
I checked the old source in both cases there where no messages. In current yaf there is much more feedback then before.

1.  i changed the code now sub forums are unbind from the parent forum, there is no need to delete a sub forum
2.   there is no message because it is logged to the event log. so every admin can see who suspended a user and when. But i added a message now
