### ISSUE TITLE
Adding DIV to logo section

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#786]
I think it is good idea to add a <DIV></DIV> or own CSS rule to the logo section and move all inline styles to the theme CSS so that it can be styled more easily.

`<asp:HyperLink runat="server" id="BannerLink">
    <asp:Image runat="server" ID="ForumLogo" Width="276" Height="128">
    </asp:Image>
</asp:HyperLink>`

To

`<div><asp:HyperLink runat="server" id="BannerLink">
    <asp:Image runat="server" ID="ForumLogo" class="LogoSection">
    </asp:Image>
</asp:HyperLink></div>`

**Comment by w8tcha** [comment]
To understand why there is the inline styles instead of in the themes or the forum.css is because the default.aspx is usually modfiied by the site owners, you would also change the meta tags. 

Its way more easier to change the image dimensions in on file instead of all the theme files.

The class is also not needed you can apply styling directly via the id instead of the class. By styling via the id also an div wrapper is not neeeded.
