### ISSUE TITLE
Support Website Down?

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#925]
Everything okay with https://yetanotherforum.net?

I've tried on my work laptop (Windows 10). Tried on my phone (Galaxy S23). Website keeps showing up like this.

![image](https://github.com/YAFNET/YAFNET/assets/5612416/878ca01d-f5f2-4314-bf3b-04bb82f414eb)

**Comment by billd2** [comment]
It has been offline for approx. two weeks I think.

Hoping it comes back soon - I have just finished porting a 25,000 user, 150,000 post forum to YAF and I have a few questions I want to ask the community!

BillD

**Comment by w8tcha** [comment]
I'm aware of that. The server is completely dead and need a new install. Unfortunately is not in my power to do that.

My plan is im looking currently to switch to a hosted site instead of an entire server hosting.

As soon as I have a solution, and the backup of the site including the db. I can bring the site back online.

**Comment by KevinDuganJr** [comment]
> I'm aware of that. The server is completely dead and need a new install. Unfortunately is not in my power to do that.
> 
> My plan is im looking currently to switch to a hosted site instead of an entire server hosting.
> 
> As soon as I have a solution, and the backup of the site including the db. I can bring the site back online.

I couldn't find anything acknowledging you knew, my bad. Hope ya get a solution that meets your needs sooner than later!

**Comment by w8tcha** [comment]
Server is back online, with an older backup
