### ISSUE TITLE
Upgrade CKEditor

### ISSUE THREAD

**Issue by muflihmajid** [YAFNET/YAFNET#938]
Hi

I have a question, regarding Ckeditor, that one still uses CKeditor 4. 
can we upgrade it becomes Ckeditor 5?

Thankyou

**Comment by w8tcha** [comment]
The problem is that ckeditor 4 and ckeditor 5 are 2 complete different editors.

So this would not be an upgrade rather then a switch to a different editor.

But at the moment the editor does not support for the bbcode mode. 

Also there is zero benefit in switching to ckeditor 5. not to forgot in the hours it would take to rewrite all plugins.

**Comment by muflihmajid** [comment]
So, it's ok if not upgrade it? Because CKEditor 4 is currently at the end of support and end of life.

**Comment by w8tcha** [comment]
Of course its no problem to continue to use the editor. And again there is no upgrade option!
