### ISSUE TITLE
Upgrade from YAF 1.9.6.1 to latest version

### ISSUE THREAD

**Issue by gromavic** [YAFNET/YAFNET#964]
Hi!

Could I upgrade forum from version  1.9.6.1 to the latest (for ex. using this archive YAF.SqlServer-v3.1.14-Upgrade)?
or Should I upgrade YAF step by step? from one version to next that provided in releases on your git?

**Comment by w8tcha** [comment]
Yes you can directly upgrade from that version, but as always make a backup of the database before the upgrade.

**Comment by KevinDuganJr** [comment]
If you notice errors when you try saving Admin Board Settings or Host Settings, check your yaf_Registry. When I upgraded that was a problem spot for me because some of my Registry records had BoardId = 1 when they were supposed to be NULL.  This could also be isolated to just me, but thought I'd mention it in case it's not. You'll really enjoy the latest version a lot! The new editor is fantastic!
